production:
  login: "***REMOVED***"
  password: "***REMOVED***"
  signature: "***REMOVED***"
staging:
  login: "***REMOVED***"
  password: "***REMOVED***"
  signature: "***REMOVED***"
development:
  login: "***REMOVED***"
  password: "***REMOVED***"
  signature: "***REMOVED***"
test:
  login: sandbox