import_mass_uploads_from_remote:
  cron: "0 7 * * *"
  class: MassUploadsImportWorker
  queue: mass_upload
  args: ["http://10.0.0.4/export/Export-{DATE}-{COUNT}.csv",13]
  description: "Imports Mass Uploads from external source to User every day at 7am"

activate_finished_mass_uploads:
  cron: "0 */3 * * *"
  class: MassUploadsActivationWorker
  queue: mass_uploads_finish
  args: [13]
  description: "Activate finished Mass Uploads for User every third hour"

#export_mass_upload_errors:
#  cron: "0 10 * * *"
#  class: MassUploadsErrorExportWorker
#  queue: mass_uploads_finish
#  args: [13]
#  description: "Exports errored Mass Uploads for User every day"

check_for_finished_mass_uploads:
  cron: "*/10 * * * *"
  class: MassUploadsFinishWorker
  queue: mass_uploads_finish
  description: "Checks if mass uploads have finished every 10 minutes"

calculate_library_popularities:
  cron: "30 0 * * 1,4"
  class: LibraryPopularitySpawnerWorker
  queue: statistics
  description: "Calculates popularity count for libraries twice a week"

export_csv_for_affiliate_marketing:
  cron: "0 2 1 * *"
  class: BelboonArticleExporterWorker
  queue: belboon_csv_export
  description: "Exports articles as CSV file for Belboon affiliate marketing once a month"

delete_old_articles:
  cron: "0 12 * * 2"
  class: OldArticleDeletionWorker
  queue: cleanup
  description: "Deletes old articles once a week"

disable_queue_at_daytime:
  cron: "0 8 * * *"
  class: QueueDisablerMetaWorker
  queue: sidekiq_pro
  description: "Disables file normalizer worker at daytime"

enable_queue_at_nighttime:
  cron: "0 0 * * *"
  class: QueueEnablerMetaWorker
  queue: sidekiq_pro
  description: "Enables file normalizer worker at nighttime"
